language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.cache
install:
  - "npm install"
  - "npm install cypress@3.4.1 --save-dev"
before_script:
  - "npm run lint"
  - "serve --no-clipboard &"
script:
  - "npm test"
  - kill $(jobs -p) || true