language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.cache
install:
<<<<<<< HEAD
  - "npm install cypress@3.4.1 --no-save"
=======
  - "npm install -g cypress-3.4.1"
>>>>>>> parent of 8fc28cb... Npm: remove cypress dev-depends. Travis: install cypress global.
  - "npm install"
before_script:
  - "npm run lint"
  - "serve --no-clipboard &"
script:
  - "$(npm bin)/cypress run"
  - kill $(jobs -p) || true